### ISSUE TITLE
High Contrast hybrid.png

### ISSUE THREAD

**Issue by thejerrod** [TrezorHannes/Dual-LND-Hybrid-VPS#1]
I created a high contrast version
![Hybrid](https://user-images.githubusercontent.com/25254103/159563667-45b53c73-3a13-425e-82a2-bf1ea65cdb7c.png)

**Comment by TrezorHannes** [comment]
Thank you for adding this. 

Since I'm using github dark mode, I wasn't aware it wasn't easy to digest.
Uploaded a new version since, let me know if mine works for you, too.
