### ISSUE TITLE
Peers unable to open to my clearnet.

### ISSUE THREAD

**Issue by lncyberhub** [TrezorHannes/Dual-LND-Hybrid-VPS#2]
Everything looks fine from my node and from my vps, as far as I can tell. 

`curl ifconfig.me` on my lightning node checks out with 137.184.232.43
`sudo ufw status` on my digital ocean vps shows port 9735 open from anywhere for LND Main Node 1

But checking port 9735 at 137.184.232.43 using https://portchecker.co shows the port closed. 

`sudo ufw status` on my lnd node does not show port 9735
Do I need to `sudo ufw allow 9735 comment 'LND'` from my node terminal? 

Maybe my recent change to lnd.conf is the problem, swamping my port? I did `numgraphsyncpeers=10` trying to improve my graph data.

Thanks so much for your help.

Here is the comment chain trying to sort the issue: https://lightningnetwork.plus/swaps/8189

**Comment by lncyberhub** [comment]
Yes! Port 9735 is open! https://portchecker.co

I needed to run `sudo ufw allow 9735 comment 'lnd-vpn-port'` as explained in the guide over on https://lightningnetwork.plus/posts/137

It makes sense, but I hesitated doing this command because I couldn't find it in this guide.

**Comment by TrezorHannes** [comment]
Hey sorry missed that issue earlier.

I actually can't remember if my raspiblitz had ufw allow 9735 from the start. Presumably, Tor doesn't need the ufw exception, but hybrid or clearnet usually does. I'll add this to the guide to ensure it's not overlooked, thank you.
